stages:
  - test

variables:
  GIT_STRATEGY: fetch
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

default:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .cargo/ # działa ponieważ ustawiliśmy CARGO_HOME w katalogu projektu
      - target/ # Zakomentuj gdy chcesz by od zera się budowało, potem możesz odkomentować
  before_script:
    - echo $CI_PIPELINE_ID
    - rustc --version && cargo --version

test:
  stage: test
  image: "rustdocker/rust:stable"
  script:
    - cargo fmt -- --check
    - cargo verify-project
    - cargo clippy --all-features --tests -- -D warnings
    - cargo build --all-features --release
    - cargo test --all-features --release --verbose
    - cargo build --release


